### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by SergeyShablenko** [webpack/json-loader#19]
I`m trying to build angular with webpack, and this is what i have, can somebody help me?
##### webpack.config.js
```
'use strict';

var path = require('path');
var webpack = require('webpack');

module.exports = {
  context: path.join(__dirname, '/'),
  entry: {
    app: ['./app/main.ts']
  },
  output: {
    path: path.join(__dirname, 'server/public/javascripts'),
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.ts', '.js', '.json']
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json' },
      { test: /\.ts$/, loader: 'ts-loader'}
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      'System': require('systemjs')
    })
  ]
};
```
##### error log
```
Module parse failed: /home/sergey/projects/vk-app/node_modules/ts-loader/index.js!/home/sergey/projects/vk-app/app/main.ts Converting circular structure to JSON
You may need an appropriate loader to handle this file type.
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Parser.<anonymous> (/home/sergey/projects/vk-app/node_modules/webpack/lib/ProvidePlugin.js:36:86)
    at Parser.applyPluginsBailResult (/home/sergey/projects/vk-app/node_modules/webpack/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.walkIdentifier (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:684:21)
    at Parser.walkExpression (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkMemberExpression (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:677:7)
    at Parser.walkExpression (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkCallExpression (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:657:9)
    at Parser.walkExpression (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkExpressionStatement (/home/sergey/projects/vk-app/node_modules/webpack/lib/Parser.js:360:7)
 @ multi app
```

**Comment by SergeyShablenko** [comment]
Close this issue, i wrote bullshit, systemjs can not be included like that, and it is not how it should be used
