### ISSUE TITLE
Correct usage?

### ISSUE THREAD

**Issue by SystemParadox** [webpack/json-loader#32]
The README just shows a weird require `!json` statement.

Please could we have some examples, both for config file and command line usage.

I am trying the following, but it results in an error:

```
$ webpack --entry ./foo.js --output-filename server.js --module-bind json

/home/simon/npm/lib/node_modules/webpack/lib/NormalModuleFactory.js:217
                        return callback(null, Object.assign({}, item, {
                                                     ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at /home/simon/npm/lib/node_modules/webpack/lib/NormalModuleFactory.js:217:33
    at onResolved (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:72:10)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:210:15
    at /home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:22
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:210:15
    at /home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:23
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:135:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:112:35)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:21:36
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/simon/npm/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:210:15
    at /home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:29:14
    at loggingCallbackWrapper (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at innerCallback (/home/simon/npm/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:22)
```

Thanks.

**Comment by bebraw** [comment]
Which version of Node are you using? Older ones are missing `Object.assign`. I would recommend updating to at least Node 4 or 6.

**Comment by SystemParadox** [comment]
Ah yes, it's my appallingly outdated version of node.

However, my request still stands, it would be helpful to have some examples.

Thanks.
